### ISSUE TITLE
Organize your code 

### ISSUE THREAD

**Issue by Jhooomn** [lucaspiano/springboot_rest_api_crud_operation#1]
- Separate "converter-methods" of your infrastructure controller impl, you must give to each class a responsibility.

- Don't use entity classes in controllers or ports, you must let it in inside @Service method classes and receive-return your DTO objects.

- Better use Stream API and stop using for-each way.

You must watch: 

* https://medium.com/backticks-tildes/the-s-o-l-i-d-principles-in-pictures-b34ce2f1e898

* https://www.baeldung.com/java-8-streams

* You must use lombok dependency on your projects to reduce pojo classes verbose way --> https://projectlombok.org/features/all

**Comment by lucaspiano** [comment]
Hi, @Jhooomn . 
Thank you very much for your analysis on my code and I agree with you.
Well, I'm learning some topics you've mentioned and that's why I've done this exercise. Gonna focus on transforming this code following these principles you've asked me to follow for the good of the code maintainance, readability and OO design.
But I can't forget to mention that I was using this idea of conversion from this article below and the writer used the conversion also in the Controller layer. 

https://www.baeldung.com/entity-to-and-from-dto-for-a-java-spring-application

Thank you.

**Comment by Jhooomn** [comment]
I hope you can solve this refactor-problem, if you want u can contact with me..
